language: php
php:
  - 8.2
language: node_js

dist: bionic

services:
  - docker

cache:
  directories:
   - $HOME/.docker/cli-plugins

before_install:
  - curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o ~/.nvm/nvm
  - source ~/.nvm/nvm.sh
  - nvm install 5
  - node --version

jobs:
  include:
    - stage: "install compose"
      script:
      - mkdir -p /home/travis/.docker/cli-plugins/
      - curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
      - chmod +x ~/.docker/cli-plugins/docker-compose
      - docker compose version
    - stage: "run compose"
      script:
      - docker compose up -d
      - docker ps
    - stage: "run tests"
      script:
      - vendor/bin/phpunit

script:
  - vendor/bin/phpunit
